// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPersonalWebsite.Models;

#nullable disable

namespace MyPersonalWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719145330_AddUserSystem")]
    partial class AddUserSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MyPersonalWebsite.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "\r\n                        <h2>🎉 开篇之作</h2>\r\n                        <p>欢迎来到我的个人网站！这是我用 ASP.NET Core 10.0 制作的第一篇博客。</p>\r\n                        <p>这个网站将会记录我的：</p>\r\n                        <ul>\r\n                            <li>技术学习心得</li>\r\n                            <li>项目开发经验</li>\r\n                            <li>编程技巧分享</li>\r\n                            <li>生活感悟随笔</li>\r\n                        </ul>\r\n                        <p>希望通过这个平台，能够和大家交流技术，共同进步。</p>\r\n                        <blockquote class='blockquote'>\r\n                            <p class='mb-0'>代码改变世界，技术创造未来。</p>\r\n                            <footer class='blockquote-footer'>Chris Hopper</footer>\r\n                        </blockquote>\r\n                    ",
                            CoverImageUrl = "/images/blog1.jpg",
                            PublishDate = new DateTime(2026, 7, 19, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "这是我的第一篇博客，欢迎大家来到我的技术空间！",
                            Title = "我的第一个博客 - 欢迎来到 Chris 的技术空间"
                        });
                });

            modelBuilder.Entity("MyPersonalWebsite.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MyPersonalWebsite.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechStack")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "使用 ASP.NET Core 10.0 构建的个人博客与作品展示网站",
                            ImageUrl = "/images/project1.jpg",
                            Name = "个人网站项目",
                            ProjectUrl = "https://github.com/chrishopper/personal-website",
                            TechStack = "ASP.NET Core 10.0, Entity Framework Core, SQLite, Bootstrap 5"
                        },
                        new
                        {
                            Id = 2,
                            Description = "更多精彩项目正在开发中，敬请期待...",
                            ImageUrl = "/images/project2.jpg",
                            Name = "待开发项目 2",
                            ProjectUrl = "#",
                            TechStack = "即将公布"
                        });
                });

            modelBuilder.Entity("MyPersonalWebsite.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerificationCodeExpiry")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "2908685235@qq.com",
                            IsAdmin = true,
                            IsEmailVerified = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEJ4Zj6zVqZMjSx5k5r5WYg==",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
